- shepherd
- The `detach` option has been added in [17.05](https://github.com/moby/moby/blob/9ff8068ca2bb1ba308ceec8f6a6ccb0fe7e7e746/docs/deprecated.md#asynchronous-service-create-and-service-update). Make sure not to use it on an older server version
- The service wasn't working when `SLEEP_TIME` was unset
> Fixes for 0.2

- README.md
- shepherd
This PR includes a change by @pdeveltere and a README enhancement by me. It allows using shepherd for private registries.
Tested with Docker 18.03.0-ce. Closes #6
> Support for private registry authentication

- Dockerfile
- README.md
- shepherd
This would allow for filtering the list of services to update using a `FILTER_SERVICES` env var. It should work with any value you can give to the `--filter` option in `docker service ls`. For example, if you only want to update services with an `autodeploy` label, set `FILTER_SERVICES="label=autodeploy"`. This might resolve #9.
> Filtering services

- shepherd
The service name can be extracted directly from `docker service ls` without the need for a second call for every service.
This PR drops the `service` variable in favor for using the `name` variable consistently.
> Removes extra docker call for the service name

- shepherd
Hi @djmaze!
You have done an amazing job with this tool. Thanks!
I had the same problem that @rmie, so I have applied the change that he suggest in #28, then I realized that it was breaking shepherd script execution, so I added an exit code validation.
Could you review my changes? It would be great having this fixed in the official image.
> Do not kill services if image download fails

- README.md
- shepherd
Add support to connect to an insecure Docker registry.
Test on my local implementation.
> Support of insecure registry

- README.md
- shepherd
On my setup, I am using image with an incoherent architecture information.
:-(
To deploy theses images, I need to use the --no-resolve-image flag on service update command
> Support of no-resolve-image flag for image update

- README.md
- shepherd
This option is created in order to clean old images after update
> Add image autocleaner

- README.md
- shepherd
Hello,
first of all, congrats for the job with shepherd, it helps a lot the CI/CD environment on PencilLabs, a tech brazilian company that i'm cofounder and developer.
This MR renames the `BLACKLIST_SERVICES`  env variable to `IGNORELIST_SERVICES`. As a black man and developer we must avoid using racist terms that the tech industry for so long has normalized. At Pencillabs, our swarm cluster already is using a custom shepherd image with `IGNORELIST_SERVICES`, so we can tag a shepherd version with `BLACKLIST_SERVICES`, to avoid breaking other environments.
> Renames BLACKLIST_SERVICES variable

- .drone.yml
- Dockerfile
Cross-builds all images on a single drone runner. Uses a custom docker-in-docker image with up-to-date armhf support.
> drone: (Cross-)build with buildx

- README.md
- shepherd
Login to the given registry before each batch of updates.
closes #60, #42
Up for testing as `mazzolino/shepherd:pr-61`.
> Allow configuring a registry login

- README.md
- shepherd
`docker service update` will exit with `1` and write something like `service update paused: update paused due to failure or early termination of task ...` to stderr if the updated service fails to start or remains unhealthy.
By setting the `ROLLBACK_ON_FAILURE` variable if an update fails Shepherd will roll it[1] back to the previous version, thus avoiding a service failure as a result of the update. If the Apprise Sidecar is set it will also send a notification about this.
[1]: https://docs.docker.com/engine/reference/commandline/service_update/#roll-back-to-the-previous-version-of-a-service
> Add support for rolling back on a failed update

- README.md
Don't ask how many tries it took me to find out about the caveat regarding the quotation marks :wink:
> Add help text and example for setting the timezone

- README.md
- shepherd
Signed-off-by: BAUDUIN Raphaël <rbauduin@users.noreply.github.com>
> support docker secrets for registry password retrieval

- README.md
- shepherd
I saw you merged my previous PR while I was finalizing this. 
It makes it possible to have all authentication info in a docker secret file, and it also allows authenticating to one registry with different accounts. This last point requires the container to be updated to be labeled accordingly to identify which authentication information to use. See the README changes for details. Let me know what you think, it works fine for me.
> support auth to multiple regs in secret file

- README.md
- docker-compose.swarm-cronjob.yml
> Add example for usage with swarm-cronjob

- shepherd
This PR fixes the currently broken handling of the VERBOSE parameter.
Setting the value is currently ignored and verbose mode is effectively enabled by default.
The PR keeps the current behavior of verbose mode being enabled by default.
> Fix defunc VERBOSE handling

- .github/workflows/build.yml
- shepherd
This PR addresses some low hanging fruits and adds a github action that automatically runs shellcheck.
> Minor refactoring

- README.md
In case the user use secret, the code reference the `REGISTRIES_FILE`, but secret by itself is not used at all by default. Either the code auto detect secret file, or without changing the code, we need to set the `REGISTRIES_FILE` to the secret file in order to pick it.
> Add documentation about `REGISTRIES_FILE`

- README.md
- examples/docker-compose.apprise.yml
- examples/docker-compose.swarm-cronjob.yml
> Move example configs to their own folder

- README.md
- shepherd
> Restrict runtime of "docker service update" using "timeout"

- README.md
the previous desctiption is misleading, official doc reads: "Do not query the registry to resolve image digest and supported platforms"
Yes, you can "force image deployment" but then it does never pull images from the registry.
https://docs.docker.com/engine/reference/commandline/service_update/
> correct misleading description of WITH_NO_RESOLVE_IMAGE

- .github/workflows/build.yml
- .github/workflows/release.yml
This PR adds a github workflow that should be roughly equal to the drone build. It also adds simple image building to the `Build` workflow so that it now both runs shellcheck and tries to build the docker image.
What it doesn't do right now is pushing said docker image to any repository (for PRs). Perhaps this could be done the same way as before (tagging as PR-xxx), but only pushing those to GHCR (to keep them out of the "official" space)?
Speaking of which, this only pushes to GHCR currently since the docker repository (`mazzolino/shepherd`) hasn't been transferred to `containrrr/shepherd`.
> ci: add basic github actions for build/release

- README.md
I just spent sometime debugging my shepherd service, why it's not using my second registry. I tracked the error down to a missing empty line at the end of my registries file. This should be present because otherwise this [read](https://github.com/containrrr/shepherd/blob/01d070aa8d94a684ec41750d92c8f8ee1dab79ca/shepherd#L35) will skip the last line. This behavior is explained here: https://stackoverflow.com/a/729795/1752287
I enhanced the README.md file for saving future users from going down that rabbit hole as well.
> Enhance documentation regarding registries file

- shepherd
As stated [here](https://docs.docker.com/engine/swarm/services/#:~:text=Note%20that,.), you should not pass other flags with the `--rollback` flag. Otherwise, you will get this error message:
```
other flags may not be combined with --rollback
```
And this error causes the shepherd container to exist with a non-zero exit code:
```
ID             NAME             IMAGE                       NODE   DESIRED STATE   CURRENT STATE            ERROR                       PORTS
mt76rdcbfaaz   shepherd.1       mazzolino/shepherd:latest   main   Running         Running 13 minutes ago
j1hi6zqylbdn    \_ shepherd.1   mazzolino/shepherd:latest   main   Shutdown        Failed 13 minutes ago    "task: non-zero exit (1)"
xyj7e0r52vog    \_ shepherd.1   mazzolino/shepherd:latest   main   Shutdown …
```
> Fix: other flags may not be combined with `--rollback`

- shepherd
Improved a bit the Apprise notification handling:
- made `curl` silent so we don't see the ugly progess bar in the logs anymore
- adapted the notification type parameter (depends on this PR: https://github.com/djmaze/apprise-microservice/pull/8)
- refactored code to extract the notification sending in a separate function to reduce code duplication
- added a log entry to indicate whether the notification was successful or not with the `curl` result
> Improve notifications handling
